// Mocks generated by Mockito 5.4.6 from annotations
// in inmobarco_app/test/data/repositories/appointment_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:inmobarco_app/core/services/notification_service.dart' as _i2;
import 'package:inmobarco_app/data/services/sync_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationService_0 extends _i1.SmartFake
    implements _i2.NotificationService {
  _FakeNotificationService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i3.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationService get notificationService =>
      (super.noSuchMethod(
            Invocation.getter(#notificationService),
            returnValue: _FakeNotificationService_0(
              this,
              Invocation.getter(#notificationService),
            ),
          )
          as _i2.NotificationService);

  @override
  _i4.Future<int> get pendingCount =>
      (super.noSuchMethod(
            Invocation.getter(#pendingCount),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  void startListening() => super.noSuchMethod(
    Invocation.method(#startListening, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> enqueue({
    required String? action,
    required String? localId,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [], {
              #action: action,
              #localId: localId,
              #payload: payload,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> purgeLocalId(String? localId) =>
      (super.noSuchMethod(
            Invocation.method(#purgeLocalId, [localId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncPendingQueue() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingQueue, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> fullSync() =>
      (super.noSuchMethod(
            Invocation.method(#fullSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> pullFromServer() =>
      (super.noSuchMethod(
            Invocation.method(#pullFromServer, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setOnPullCompleted(_i5.VoidCallback? callback) => super.noSuchMethod(
    Invocation.method(#setOnPullCompleted, [callback]),
    returnValueForMissingStub: null,
  );
}
