// Mocks generated by Mockito 5.4.6 from annotations
// in inmobarco_app/test/ui/providers/appointment_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i3;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i7;
import 'package:inmobarco_app/core/services/notification_service.dart' as _i6;
import 'package:inmobarco_app/data/repositories/appointment_repository.dart'
    as _i2;
import 'package:inmobarco_app/domain/models/appointment.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppointmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRepository extends _i1.Mock
    implements _i2.AppointmentRepository {
  MockAppointmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onDataChanged(_i3.VoidCallback? value) => super.noSuchMethod(
    Invocation.setter(#onDataChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i5.Appointment>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i5.Appointment>>.value(
              <_i5.Appointment>[],
            ),
          )
          as _i4.Future<List<_i5.Appointment>>);

  @override
  _i4.Future<void> saveAll(List<_i5.Appointment>? appointments) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [appointments]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int?> syncCreate(_i5.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#syncCreate, [appointment]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<void> syncUpdate(_i5.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#syncUpdate, [appointment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncDelete(String? localId, int? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#syncDelete, [localId, serverId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> purgeLocalId(String? localId) =>
      (super.noSuchMethod(
            Invocation.method(#purgeLocalId, [localId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleAppointmentReminder(_i5.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleAppointmentReminder, [appointment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAppointmentReminder(String? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAppointmentReminder, [appointmentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rescheduleAppointmentReminder(
    _i5.Appointment? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rescheduleAppointmentReminder, [appointment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showTestNotification() =>
      (super.noSuchMethod(
            Invocation.method(#showTestNotification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingNotifications, []),
            returnValue: _i4.Future<List<_i7.PendingNotificationRequest>>.value(
              <_i7.PendingNotificationRequest>[],
            ),
          )
          as _i4.Future<List<_i7.PendingNotificationRequest>>);
}
